<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>CInstaller</AssemblyName>
        <ApplicationIcon>CInstaller.ico</ApplicationIcon>
        <Version>0.1.1</Version>
        
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <OutputType>WinExe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    </PropertyGroup>

    <ItemGroup>
      <ApplicationDefinition Include="ui\App.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </ApplicationDefinition>
    </ItemGroup>

    <ItemGroup>
      <Page Include="ui\App.xaml" />
    </ItemGroup>

</Project>
